trigger: none

pr: none

schedules:
- cron: "0 0 * * 0"
  displayName: Daily build
  branches:
    include:
    - main
  always: true

variables:
- group: azfluent

jobs:
  - job: Automation Metadata
    timeoutInMinutes: 10

    pool:
      vmImage: ubuntu-20.04

    steps:
      - script: |
          python3 eng/script/export_metadata.py --github-token=$(github-token)
        displayName: 'Export metadata'
