trigger: none

#schedules:
#- cron: "0 0 * * *"
#  displayName: Daily build
#  branches:
#    include:
#    - main

jobs:
  - job: Automation
    timeoutInMinutes: 360

    pool:
      vmImage: ubuntu-20.04

    steps:
      - script: |
          ./automation/main.sh --build-id=$(Build.BuildId) --github-token=$(GITHUB_TOKEN) --release-in-days=$(RELEASE_IN_DAYS) --persist-data=$(PERSIST_DATA)
        displayName: 'Collect examples'
